version: '3.6'

services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    # Use "host" network mode for DHCP deployments
    # network_mode: "host"
    ports:
      - "5380:5380/tcp" #DNS web console
      - "53:53/udp" #DNS service
      - "53:53/tcp" #DNS service
      # - "67:67/udp" #DHCP service
      # - "853:853/tcp" #DNS-over-TLS service
      # - "443:443/tcp" #DNS-over-HTTPS service
      # - "80:80/tcp" #DNS-over-HTTPS service certbot certificate renewal
      # - "8053:8053/tcp" #DNS-over-HTTPS using reverse proxy
    environment:
      - DNS_SERVER_DOMAIN=dns-server #The primary domain name used by this DNS Server to identify itself.
      # - DNS_SERVER_ADMIN_PASSWORD=password #DNS web console admin user password.
      # - DNS_SERVER_ADMIN_PASSWORD_FILE=password.txt #The path to a file that contains a plain text password for the DNS web console admin user.
      # - DNS_SERVER_PREFER_IPV6=false #DNS Server will use IPv6 for querying whenever possible with this option enabled.
      # - DNS_SERVER_OPTIONAL_PROTOCOL_DNS_OVER_HTTP=false #Enables DNS server optional protocol DNS-over-HTTP on TCP port 8053 to be used with a TLS terminating reverse proxy like nginx.
      # - DNS_SERVER_RECURSION=AllowOnlyForPrivateNetworks #Recursion options: Allow, Deny, AllowOnlyForPrivateNetworks, UseSpecifiedNetworks.
      # - DNS_SERVER_RECURSION_DENIED_NETWORKS=1.1.1.0/24 #Comma separated list of IP addresses or network addresses to deny recursion. Valid only for `UseSpecifiedNetworks` recursion option.
      # - DNS_SERVER_RECURSION_ALLOWED_NETWORKS=127.0.0.1, 192.168.1.0/24 #Comma separated list of IP addresses or network addresses to allow recursion. Valid only for `UseSpecifiedNetworks` recursion option.
      # - DNS_SERVER_ENABLE_BLOCKING=false #Sets the DNS server to block domain names using Blocked Zone and Block List Zone.
      # - DNS_SERVER_ALLOW_TXT_BLOCKING_REPORT=false #Specifies if the DNS Server should respond with TXT records containing a blocked domain report for TXT type requests.
      # - DNS_SERVER_FORWARDERS=1.1.1.1, 8.8.8.8 #Comma separated list of forwarder addresses.
      # - DNS_SERVER_FORWARDER_PROTOCOL=Tcp #Forwarder protocol options: Udp, Tcp, Tls, Https, HttpsJson.
      # - DNS_SERVER_LOG_USING_LOCAL_TIME=true #Enable this option to use local time instead of UTC for logging.
    volumes:
      - ./dns-config:/etc/dns/config
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000

  gitea:
    container_name: gitea
    image: gitea/gitea
    restart: unless-stopped
    environment:
      # https://docs.gitea.io/en-us/install-with-docker/#environments-variables
      - RUN_MODE=prod
      - GITEA__webhook__ALLOWED_HOST_LIST=drone.dakota.eu
      - GITEA__metrics__ENABLED=true
    ports:
      - "10022:22"
    networks:
      - cicd_net
    volumes:
      - ./gitea:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.dakota.eu`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - ./minio:/data
    user: ${UID}:${GID}
    entrypoint: sh
    command: -c 'minio server /data --console-address ":9001"'
    networks:
      - cicd_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.routers.minio.rule=Host(`s3.dakota.eu`)"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.rule=Host(`minio.dakota.eu`)"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

  drone:
    container_name: drone
    image: drone/drone:2.8.0
    restart: unless-stopped
    depends_on:
      - gitea
    environment:
      - DRONE_GITEA_SERVER=http://gitea.dakota.eu/
      - DRONE_RPC_SECRET=34618ee909cb804b2d059fa1b3905cf5
      - DRONE_RUNNER_CAPACITY=4
      - DRONE_SERVER_PROTO=http
      - DRONE_SERVER_HOST=drone.dakota.eu
      - DRONE_NETWORK=cicd_net
      - DRONE_RUNNER_NETWORKS=cicd_net
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_S3_ENDPOINT=http://minio:9000
      - DRONE_S3_BUCKET=drone
      - DRONE_S3_SKIP_VERIFY=true
      - DRONE_S3_PATH_STYLE=true
      - AWS_ACCESS_KEY_ID=drone
      - AWS_SECRET_ACCESS_KEY=drone-secret
        #- AWS_ACCESS_KEY_ID=drone
        #- AWS_SECRET_ACCESS_KEY=34618ee909cb804b2d059fa1b3905cf5
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_REGION=us-east-1
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_USER_CREATE=username:prometheus,machine:true,admin:true,token:34618ee909cb804b2d059fa1b3905cf5
    networks:
      - cicd_net
    volumes:
      - ./drone:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`drone.dakota.eu`)"
      - "traefik.http.routers.drone.entrypoints=web"

  drone-agent:
    container_name: drone_runner
    image: drone/drone-runner-docker:1.8.0
    restart: unless-stopped
    depends_on:
      - drone
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_SECRET=34618ee909cb804b2d059fa1b3905cf5
      - DRONE_RUNNER_NAME=runners
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_NETWORK=cicd_net
      - DRONE_RUNNER_NETWORKS=cicd_net
      - DRONE_LOGS_DEBUG=true
      - DRONE_LOGS_TEXT=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true
      - DRONE_LOGS_TRACE=true
    networks:
      - cicd_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  s3www:
    image: y4m4/s3www:latest
    container_name: s3www
    command:
      - "-endpoint=http://minio:9000"
      - "-accessKey=webreader"
      - "-secretKey=webreader-secret"
      - "-bucket=public"
      - "-address=0.0.0.0:8080"
    restart: unless-stopped
    networks:
      - cicd_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.www.rule=Host(`dakota.eu`)"
      - "traefik.http.routers.www.entrypoints=web"

  proxy:
    image: traefik
    container_name: "traefik"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--accesslog=true"
      - "--metrics"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
    restart: unless-stopped
    networks:
      - cicd_net
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.routers.traefik.rule=Host(`traefik.dakota.eu`)" # Change this to your domain
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"

networks:
  cicd_net:
    name: cicd_net

volumes:
    config: