{
 "title": "Docker monitoring",
 "description": "A simple overview of the most important Docker host and container metrics. (cAdvisor/Prometheus)",
 "tags": [
  "docker",
  "system"
 ],
 "time": { "from": "2022-01-16T22:49:11.022Z", "to": "2022-01-17T00:49:11.022Z" },
 "refresh": "5s",
 "panels": [
  { "title": "Containers stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[3m])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[5m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Swap per Container",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_swap{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total used memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"})",
     "legendFormat": "{{RAM}}"
    }
   ]
  },
  { "title": "Focus CPU/RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage per Container",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m])) by (name) * 100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(container_memory_rss{name=~\".+\"}) by (name))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Host stats & graph",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load [1m]",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(node_load1) /  count(count(node_cpu_seconds_total) by (cpu))"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100"
      }
     ]
    },
    {
     "title": "Swap",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_SwapTotal_bytes{instance=~'$server:.*'} - node_memory_SwapFree_bytes{instance=~'$server:.*'})"
      }
     ]
    },
    {
     "title": "Disk space",
     "type": "gauge",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "min((node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"} - node_filesystem_free_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"} )/ node_filesystem_size_bytes{fstype=~\"xfs|ext4\",instance=~\"$server:.*\"})"
      }
     ]
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "time() - node_boot_time_seconds"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum ( irate(node_cpu_seconds_total{mode!='idle',instance=~\"$server:.*\"}[5m]))",
       "legendFormat": "cpu"
      }
     ]
    },
    {
     "title": "Disk I/O",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "-irate(node_disk_read_bytes_total[5m])",
       "legendFormat": "OUT on /{{device}}"
      },
      {
       "expr": "irate(node_disk_written_bytes_total[5m])",
       "legendFormat": "IN on /{{device}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total[5m]))",
       "legendFormat": "RECEIVED"
      },
      {
       "expr": "- sum(irate(node_network_transmit_bytes_total[5m]))",
       "legendFormat": "SENT"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "node_memory_MemTotal_bytes", "legendFormat": "RAM Total" },
      {
       "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
       "legendFormat": "RAM Used"
      }
     ]
    }
   ]
  }
 ]
}