---
kind: pipeline
name: python-3-6

steps:
- name: test
  image: python:3.6
  commands:
  - pip install -r requirements.txt
  - python3 -m unittest discover -p '*_test.py' tests/
---
kind: pipeline
name: python-3-8

steps:
- name: test
  image: python:3.8
  commands:
  - pip install -r requirements.txt
  - python3 -m unittest discover -p '*_test.py' tests/
